Brought over as many bugfixes & features from the 0.17.x branch as I felt were safe to bring over at this time.

diff --git a/freebsd/Makefile.am b/freebsd/Makefile.am
--- a/freebsd/Makefile.am
+++ b/freebsd/Makefile.am
@@ -1,6 +1,40 @@
 
-EXTRA_DIST	= 5250keys\
+EXTRA_DIST	= us.5250.kbd\
+		  5250keys\
 		  README\
-                  sample.termcap\
-                  us.5250.kbd
+		  sample.termcap
+
+pkgdata_DATA	= us.5250.kbd \
+		  sample.termcap \
+		  README
+
+bin_SCRIPTS 	= 5250keys
+
+#
+# here we install our termcap entry 
+#
+install-data-local:
+	@( good=no ; \
+	  if [ "`uname -s`" = "FreeBSD" ]; then \
+              grep -q "xterm-5250" /usr/share/misc/termcap || good=yes; \
+              if [ x$$good = xyes ]; then \
+		  echo "Adding termcap entry..." ; \
+	          cat sample.termcap >> /usr/share/misc/termcap ; \
+                  cap_mkdb /usr/share/misc/termcap ; \
+	      fi ; \
+	  else \
+	      good=yes ; \
+	  fi ; \
+	  if [ x$$good = xno ] ; then \
+	    echo "**" >&2 ; \
+	    echo "** Could not install termcap entry automatically.  Possible" >&2 ; \
+	    echo "** reasons for this include:" >&2 ; \
+	    echo "**   - You already had an xterm-5250 in your termcap " >&2 ; \
+	    echo "**   - termcap isn't installed in its usual place " >&2 ; \
+	    echo "**" >&2 ; \
+	    echo "** Some keys may not work until this is installed, please read" >&2 ; \
+	    echo "** the freebsd/README file for instructions on how to install" >&2 ; \
+	    echo "** this manually." >&2 ; \
+	    echo "**" >&2 ; \
+	  fi )
 
